// Generated by scripts/build-previews.mjs. Lesson bodies are fetched on demand.
export const PREVIEWS = [
  {
    "slug": "weather-and-clothes",
    "title": "Weather and Clothes",
    "level": "A1",
    "age": "5-7",
    "minutes": 45,
    "skill": "Listening",
    "summary": "Name five pictures, listen for details, and choose clothes for a simple situation.",
    "step": 1,
    "hash": "75b1e2fdfee7"
  },
  {
    "slug": "toys-and-play",
    "title": "Toys and Play",
    "level": "A2",
    "age": "8-9",
    "minutes": 45,
    "skill": "Speaking",
    "summary": "Move from naming toys to polite requests and a short partner exchange.",
    "step": 2,
    "hash": "b4974a9db0a3"
  },
  {
    "slug": "food-at-a-restaurant",
    "title": "Food at a Restaurant",
    "level": "A2",
    "age": "Adults (20-23)",
    "minutes": 60,
    "skill": "Speaking",
    "summary": "Use a menu, make an order, handle one unavailable item, and ask for the bill.",
    "step": 3,
    "hash": "868940c2b3b7"
  },
  {
    "slug": "teen-life-and-free-time",
    "title": "Teen Life and Free Time",
    "level": "B1",
    "age": "13-15",
    "minutes": 60,
    "skill": "Speaking",
    "summary": "Compare two hobbies, explain a preference, and negotiate a club choice.",
    "step": 4,
    "hash": "dd0a968df681"
  },
  {
    "slug": "solving-everyday-problems",
    "title": "Solving Everyday Problems",
    "level": "B2",
    "age": "13-15",
    "minutes": 60,
    "skill": "Mixed",
    "summary": "Weigh competing solutions against time, fairness, cost, and likely consequences.",
    "step": 5,
    "hash": "fe2d253adf06"
  },
  {
    "slug": "globalization-and-culture",
    "title": "Globalization and Culture",
    "level": "C1",
    "age": "16-18",
    "minutes": 75,
    "skill": "Writing",
    "summary": "Distinguish access from control and write a qualified argument about cultural exchange.",
    "step": 6,
    "hash": "97a3a19cd172"
  },
  {
    "slug": "future-of-work",
    "title": "Future of Work",
    "level": "C1",
    "age": "16-18",
    "minutes": 75,
    "skill": "Speaking",
    "summary": "Separate tasks from jobs, question assumptions, and defend a realistic training proposal.",
    "step": 7,
    "hash": "9476f084b34f"
  },
  {
    "slug": "inequality-and-social-mobility",
    "title": "Inequality and Social Mobility",
    "level": "C2",
    "age": "Adults (20-23)",
    "minutes": 90,
    "skill": "Writing",
    "summary": "Evaluate causal claims, distinguish outcomes from mechanisms, and defend a conditional policy judgment.",
    "step": 8,
    "hash": "138ee086d76a"
  }
] as const;
export type Preview = (typeof PREVIEWS)[number];
export const previewBase = '/previews/v1/';
