/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BetaManagementRouteImport } from './routes/beta-management'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QuickStartRouteImport } from './routes/quick-start'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as LessonsIdRouteImport } from './routes/lessons.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaManagementRoute = BetaManagementRouteImport.update({
  id: '/beta-management',
  path: '/beta-management',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickStartRoute = QuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIdRoute = LessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/beta-management': typeof BetaManagementRoute
  '/builder': typeof BuilderRoute
  '/profile': typeof ProfileRoute
  '/quick-start': typeof QuickStartRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/lessons/': typeof LessonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/beta-management': typeof BetaManagementRoute
  '/builder': typeof BuilderRoute
  '/profile': typeof ProfileRoute
  '/quick-start': typeof QuickStartRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/lessons': typeof LessonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/beta-management': typeof BetaManagementRoute
  '/builder': typeof BuilderRoute
  '/profile': typeof ProfileRoute
  '/quick-start': typeof QuickStartRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/lessons/': typeof LessonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/beta-management'
    | '/builder'
    | '/profile'
    | '/quick-start'
    | '/api/generate-image'
    | '/lessons/$id'
    | '/lessons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/beta-management'
    | '/builder'
    | '/profile'
    | '/quick-start'
    | '/api/generate-image'
    | '/lessons/$id'
    | '/lessons'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/beta-management'
    | '/builder'
    | '/profile'
    | '/quick-start'
    | '/api/generate-image'
    | '/lessons/$id'
    | '/lessons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BetaManagementRoute: typeof BetaManagementRoute
  BuilderRoute: typeof BuilderRoute
  ProfileRoute: typeof ProfileRoute
  QuickStartRoute: typeof QuickStartRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  LessonsIdRoute: typeof LessonsIdRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta-management': {
      id: '/beta-management'
      path: '/beta-management'
      fullPath: '/beta-management'
      preLoaderRoute: typeof BetaManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-start': {
      id: '/quick-start'
      path: '/quick-start'
      fullPath: '/quick-start'
      preLoaderRoute: typeof QuickStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$id': {
      id: '/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof LessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BetaManagementRoute: BetaManagementRoute,
  BuilderRoute: BuilderRoute,
  ProfileRoute: ProfileRoute,
  QuickStartRoute: QuickStartRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  LessonsIdRoute: LessonsIdRoute,
  LessonsIndexRoute: LessonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
