// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'
import { readRequest } from '@/lib/read-request'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    // Bound only the session read, before dispatching the RPC. Never time out or
    // replay a mutation/paid generation that might already be running.
    const { data, error } = await readRequest(() => supabase.auth.getSession())
    if (error) throw new Error('Could not check your sign-in. Please try again.')
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
